### ISSUE TITLE
Invisible text

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/prototype_vRWOT#1]
In the opening room, there is a TIP with text that is white on a white background.
> type: look at [item]. 

The phrase "look at [item]" is effectively invisible.

**Comment by noahgibbs** [comment]
Hey @ChristopherA - this may be one where you know more than me. The tip contains something with a "syntax" atag. The syntax atag is getting sent (from the server, seems like) with a "color" attribute of #FFFF. So it's showing up white - maybe Orchil is unusual among SkotOS clients in having a white background? But do you know where atags get mapped to colours on the server?

It's also possible to change the background colour and cheat at this a bit. I'd prefer to figure out how this mapping works, though, and fix it there. If Chris doesn't know, I may just do the quick cheat fix.

**Comment by noahgibbs** [comment]
I say "from the server, seems like" because I haven't checked the exact wire protocol on this one. If you, Chris, don't know how this is set, checking the wire protocol will be step 2. And if that doesn't help quickly, just switching to one of the other built-in colour themes is probably step 3 :-)

**Comment by ChristopherA** [comment]
There are issues from the Marrach team about problems with the default colors of Orchill, and difficult with setting theming choices. We should find that issue and contact them.

**Comment by noahgibbs** [comment]
Here's the exact text as received by Orchil:

~~~
<b>TIP:</b> Our help files offer instructions on a number of basic commands. For a basic list of help resources, type or click: <a xch_cmd='@help'>@help</a>. To broader list of concepts covered by our help files, type or click: <a xch_cmd='@help concepts'>@help concepts</a>. To get help on a specific command, type type:<font color=#FFFFFF> @help [command]</font>. To learn how to get in-game assistance, type or click: <a xch_cmd='@tip'>@tip</a> again.
~~~

The Orchil issue you mention (https://github.com/ChatTheatre/orchil/issues/7) is being reflected here - colour #FFFFFF is being truncated/changed to #FFFF.

(Investigating a bit)

Oh hey, the stripQuotes() method that Orchil is using is just broken. Colours show the problem quite clearly because cutting off an extra character or two makes them look very different. But there are probably other problems with the other Alice attributes (title, xch_cmd, class.) I'll submit a PR shortly, which should also fix the reported Orchil issue above.

However, it *won't* fix the problem that DGD is saying to make the text white, but the background is white. Even parsed correctly, #FFFFFF is still white. I'm going to set the default theme to "dark" in RWOT to fix that. I'll also message the folks in the Orchil issue and see if they know how colours get mapped.

**Comment by noahgibbs** [comment]
Okay. RWOT now has a default theme of "dark" and includes the new quote-parsing fix and background_color clientpref.

If the Marrach folks get back to me about colour mapping then there may be an on-server fix. We can also do things like change the default background. I *could* do a deep dive and figure out the colour mapping with some work, but my initial assumption is that that's not worth the time.

**Comment by noahgibbs** [comment]
While I'm here, an update on this: I've fixed this in mainline ChatTheatre/SkotOS by having an Orchil mode that uses SkotOS colour themes like their older clients did. When I update RWOT with latest SkotOS it should fix this in a better way than requiring the dark colour theme.

**Comment by noahgibbs** [comment]
This is working fine in the RWOT version with updated SkotOS. There was a bug I just fixed where a female chat-body would, oddly, not get the dark server-set theme properly. But there's a PR for that in SkotOS master now.
